### ISSUE TITLE
Wrong includes in stubs

### ISSUE THREAD

**Issue by DionPotkamp** [LaravelCollective/auth#1]
Thanks for this package!

I'm now trying to use it and I noticed that the stubs for the auth controllers include their classes via `Collection\...`. Should this not be `Collective\...`?

Also the models are now located in `App\Models\...` not in `App\...`, this should probably also change. 

Not a lot of work to fix. If you don't have the time I could make a PR.

**Comment by mlantz** [comment]
Thanks - done - better late than never :)
